services:
  db:
    image: postgres:15-alpine
    container_name: ticketing-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ticketing_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - dokploy-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ticketing-backend
    ports:
      - "4000:5000" # host:container (NestJS default port 3000)
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=ticketing_app
      - JWT_SECRET=secretcoy
      - JWT_EXPIRES_IN=7d
      - FRONTEND_URL=http://frontend:3000
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=layanggroup@gmail.com
      - SMTP_PASS="urbn qdal xvgm kbad"
      - SMTP_FROM=noreply@ticketing-app.com
      - GOOGLE_CLIENT_ID=8112527535-tfti3e8aq74f4f4f9fip3pq6l7i801hj.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CALLBACK_URL=http://backend:5000/api/auth/google/callback
      - PORT=5000
      - NODE_ENV=development
      - XENDIT_PUBLIC_KEY=xnd_public_production_vf34AtLlXwlWJzrORt0uzkJOl4NVBx78HZ7L_MwKbmwaVMwa6lu8eha1AkGjbN0N
      - XENDIT_SECRET_KEY=xnd_production_tR04PhqeCuRKA5396HD1VdxrpTMeuexGfqw9qSyh5l0iAIM36mqfQMXVYuY7ru
      - XENDIT_VERIFICATION_TOKEN=yyI0FqtmZBd1yczzKHZ0dzF2bwfzabmq8cx2N03KwiqJHgox
    restart: unless-stopped
    networks:
      - dokploy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ticketing-frontend
    ports:
      - "3000:3000" # host:container (Next.js default port 3000)
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://backend:5000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - dokploy-network
